Compatibility 4.3 + 4.6
shopgate/cart-integration-gambiogx pull request #17
Opened 2022-11-02 10:10 UTC by Stereck

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I updated the CHANGELOG.md

2022-11-23 17:48 UTC, Rekhyt requested changes
Looks pretty straight forward. Only small code-style suggestions so far. Will test in a Gambio shop tomorrow.

Thank you for the PR & update.

2022-11-23 17:48 UTC, Rekhyt commented on src/shopgate/gambiogx/includes/modules/payment/ShopgateInstallHelper.php
> +        return !(TABLE_CONFIGURATION === 'gx_configurations');
```suggestion
        return TABLE_CONFIGURATION !== 'gx_configurations';
```

2022-11-23 17:48 UTC, Rekhyt commented on src/shopgate/gambiogx/includes/modules/payment/ShopgateInstallHelper.php
> +        if (!(TABLE_CONFIGURATION === 'gx_configurations')) {
```suggestion
        if ($this->useLegacyConfigTable()) {
```

2022-11-23 17:48 UTC, Rekhyt commented on src/shopgate/gambiogx/includes/modules/payment/shopgate.php
> +        return !(TABLE_CONFIGURATION === 'gx_configurations');
```suggestion
        return TABLE_CONFIGURATION !== 'gx_configurations';
```

2022-11-23 17:48 UTC, Rekhyt commented on src/shopgate/model/location/ShopgateShippingModel.php
> +        return !(TABLE_CONFIGURATION === 'gx_configurations');
```suggestion
        return TABLE_CONFIGURATION !== 'gx_configurations';
```

2022-11-25 07:52 UTC, Stereck commented
@Rekhyt thank you for the review and suggestions. Unfortunately I am missing the rights to apply them. Maybe because its a Shopgate repo or because the branch + commit is from Rainer. If you can apply them from here, can you please do so?
Otherwise just let me know and I will do it on my local and push it as suggested.

2022-11-25 08:31 UTC, Rekhyt commented
Seems like you didn't have access anymore. I applied the suggestions and fixed permissions for next time.

2022-11-25 08:33 UTC, Rekhyt requested changes

2022-11-25 08:33 UTC, Rekhyt commented on src/shopgate/gambiogx/includes/modules/payment/ShopgateInstallHelper.php
> +            $row = [];
As per PHP CS Fixer:

```suggestion
            $row = array();
```

2022-11-25 09:55 UTC, Rekhyt approved these changes

2022-11-25 10:07 UTC, Stereck commented
@Rekhyt thank you! Not sure if permissions have been updated, but I cannot merge this PR ^^

2022-11-25 12:05 UTC, Rekhyt commented
I was going to merge this anyway but good hint, permissions still weren't sufficient. Should be good now. If we ever need to touch this again.

2022-11-25 12:05 UTC, merged